name: Release and Publish Nuget

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"  
      - "[0-9]+.[0-9]+.[0-9]+-alpha" 
      - "[0-9]+.[0-9]+.[0-9]+-beta"      
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/${env:RELEASE_BRANCH}
        env:
          RELEASE_BRANCH: main

      - name: Restore dependencies
        run: dotnet restore src\SciChartBlazor.sln

      - name: Build
        run: |
          $version= &git describe --tags
          echo $version
          
          dotnet build src\SciChartBlazor.sln --no-restore --configuration Release /p:Version=$version
      - name: Test
        run: |
          $version= &git describe --tags
          dotnet test src\SciChartBlazor.sln --configuration Release /p:Version=$version --no-build
      - name: Pack
        run: |
          $version= &git describe --tags
          dotnet pack src\SciChartBlazor\SciChartBlazor.csproj --configuration Release /p:Version=$version --no-build --output .
      - name: Push
        run: |
          $version= &git describe --tags
          dotnet nuget push SciChartBlazor.${version}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${env:GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_KEY }}
